### ISSUE TITLE
A valid ReactComponent must be returned

### ISSUE THREAD

**Issue by anzgar** [reactjs/react-modal#638] opened 2018-03-31 13:07 UTC
Hello!
Sorry for a, maybe, silly issue.
I'm doing exactly as in your example, but having a error: _Uncaught Error: Invariant Violation: t.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object._ 
The final idea is to open modal while handling form submit.

`
import React from 'react';
import Modal from 'react-modal';

const formContainerID = '#ticketsForm';

const customStyles = {
    content : {
        top                   : '50%',
        left                  : '50%',
        right                 : 'auto',
        bottom                : 'auto',
        marginRight           : '-50%',
        transform             : 'translate(-50%, -50%)'
    }
};

Modal.setAppElement(formContainerID);

export default class TicketsForm extends React.Component {
    constructor(props) {
        super(props);
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);

        this.state = {
            data: {},
            items: '',
            open: false
        };

        this.openModal = this.openModal.bind(this);
        this.afterOpenModal = this.afterOpenModal.bind(this);
        this.closeModal = this.closeModal.bind(this);
    }

    openModal() {
        this.setState({modalIsOpen: true});
    }

    afterOpenModal() {
        this.subtitle.style.color = '#f00';
    }

    closeModal() {
        this.setState({modalIsOpen: false});
    }

    handleChange(event) {
        this.setState({value: event.target.value});
    }

    handleSubmit(event) {
        event.preventDefault();
        //здесь будет отсылка данных для сохранения
        this.onOpenModal();
    }

    componentDidMount() {
        //здесь будет получение данных из API
        var items = [
            {"id":"1212", "name":"Вася Пупырышкин", "email":"vasya@pup.kin"},
            {"id":"1213", "name":"Изя Кацман", "email":"izya@grad.com"},
            {"id":"1214", "name":"", "email":""}
        ];

        this.setState({
            isLoaded: true,
            items: items
        });
    }

    render() {
        var fields = [];

        for (var i = 0; i < this.state.items.length; i++) {
            var inTicket = [];
            inTicket.push(<h3>Билет №{i+1}</h3>);
            inTicket.push(
                React.createElement(
                    'input',
                    {
                        type: 'text',
                        className: 'form-control',
                        placeholder: 'Имя',
                        name: 'Tickets[' + i + '][name]',
                        defaultValue: this.state.items[i].name
                    },
                )
            );
            inTicket.push(
                React.createElement(
                    'input',
                    {
                        type: 'text',
                        className: 'form-control',
                        placeholder: 'E-mail',
                        name: 'Tickets[' + i + '][email]',
                        defaultValue: this.state.items[i].email
                    },
                )
            );

            fields.push(
                React.createElement(
                    'div',
                    {
                        className: 'col-md-12 bg-success',
                    },
                    inTicket
                )
            );
        }

        fields.push(
            <div className='col-md-12 pt-3 bg-success'>
                <button type="submit" className="btn btn-success">Сохранить</button>
            </div>
        );

        fields.push(
            <Modal open={open} onClose={this.onCloseModal} little>
                <h2>Simple centered modal</h2>
            </Modal>
        );

        return (
            <div>
                <form onSubmit={this.handleSubmit}>
                    {fields}
                </form>

                <Modal
                    isOpen={this.state.modalIsOpen}
                    onAfterOpen={this.afterOpenModal}
                    onRequestClose={this.closeModal}
                    style={customStyles}
                    contentLabel="Example Modal"
                >

                    <h2 ref={subtitle => this.subtitle = subtitle}>Hello</h2>
                    <button onClick={this.closeModal}>close</button>
                    <div>I am a modal</div>
                    <form>
                        <input />
                        <button>tab navigation</button>
                        <button>stays</button>
                        <button>inside</button>
                        <button>the modal</button>
                    </form>
                </Modal>
            </div>
        );
    }
}

ReactDOM.render(
    <TicketsForm />,
    document.getElementById('ticketsForm')
);
`

**Comment by diasbruno** [comment] 2018-04-02 02:55
Hi, @anzgar. You will need to track any variable that might be not contain a `ReactComponent`.

**Comment by diasbruno** [comment] 2018-04-02 02:58
I'm marking as `not a bug`, since it seems not related to `react-modal`, but I'll leave this open so people can help you.

**Comment by diasbruno** [comment] 2018-04-07 18:55
@anzgar Have you found a way to fix this issue?

**Comment by diasbruno** [comment] 2018-04-30 15:48
@anzgar I'll close this for clean up. Hope you could find a fix for this issue. Thanks.

**Closed by diasbruno** 2018-04-30 15:48 UTC
Labels: easy, help wanted, not a bug
