### ISSUE TITLE
当父容器上存在mouseover等事件时，modal显示后也会触发mouseover事件，有没有办法阻止呢？ 

### ISSUE THREAD

**Issue by ChenGuanglin0924** [reactjs/react-modal#684] opened 2018-09-03 02:26 UTC
当父容器上存在mouseover等事件时，modal显示后也会触发mouseover事件，有没有办法阻止呢？

**Comment by StefanYohansson** [comment] 2018-09-03 20:02
what do you mean by mouseover on parent? are you trying to prevent close the modal when clicked outside or something like this?

Describe your scenario and we can help you.

**Comment by ChenGuanglin0924** [comment] 2018-09-05 01:39
<div id="aa" onMouseOver={alert("a")}>
    <div></div>
     ......
    <Modal parentSelector={() => document.querySelector('.app-root')}></Modal>
</div>
The alert event is also triggered when the mouse is moved into Modal

**Comment by diasbruno** [comment] 2018-09-05 02:19
Thanks, @StefanYohansson, for jump in.

@ChenGuanglin0924 can you make a codepen or codesandbox with a reproducible example?

**Comment by ChenGuanglin0924** [comment] 2018-09-05 06:28
[https://codesandbox.io/s/wy1pp713k5](url) @diasbruno

**Comment by ChenGuanglin0924** [comment] 2018-09-05 06:31
[https://codesandbox.io/s/wy1pp713k5](url) @diasbruno

**Comment by diasbruno** [comment] 2018-09-05 13:05
@ChenGuanglin0924 in this case, since the modal is inside the `<div>` with the event listeners, you need to stop the propagation on those handlers, so they don't go through the modal.

**Comment by ChenGuanglin0924** [comment] 2018-09-05 13:18
React-Modal doesn't provide the way to stop the propagation, but there is one way, for example, add a `div` outside the `Modal`, and stop the propagation inside the `div`, but I don't think this method is very good, it will leave a empty `div` in the dom. @diasbruno 
`<div id="aa" onMouseOver={alert("a")}>`
`<div></div>`
`......`
`<div onMouseOver={(e)=>{e.stopPropagation()}}>`
`<Modal parentSelector={() => document.querySelector('.app-root')}></Modal>`
`</div>`
`</div>`

**Comment by diasbruno** [comment] 2018-09-05 13:52
Perhaps, for a cleaner solution, there are 2 options in this case:

1. Make the div and the modal siblings:

> This way the modal is not on the hierarchy and doesn't receive the event.

2. Control using `isOpen` property:

> I would recommend to always use this property and never keep it on a local state. It gives better control.
> You can use this state to just make the event listener a `noop`.

```js
MouseEvent(flag) {
  // note that it's a method to get the current value. I don't thing it's safe.
  // better to leave the parent component to say when the modal should be opened.
  if (this.refs.modal.isOpen()) {
    return;
  }
  ...
 }
}
```

**Comment by diasbruno** [comment] 2018-09-13 13:33
@ChenGuanglin0924 Is the comment above helped or have you solved this issue?

**Comment by diasbruno** [comment] 2018-09-17 15:19
@ChenGuanglin0924 I'll close this issue for now. Please feel free to reopen if this issue still persist. Thanks.

**Closed by diasbruno** 2018-09-17 15:19 UTC
