### ISSUE TITLE
const declaration in refCount.js is breaking compatibility with non-ES6 browsers (e.g. IE10)

### ISSUE THREAD

**Issue by enjoitheburger** [reactjs/react-modal#380] opened 2017-04-17 23:39 UTC
### Summary:
In v1.7.6, line 10 of refCount.js has a `const` instead of a `var` declared, which single-handedly seems to break compatibility with IE10.

### Steps to reproduce:

 1. Attempt to use a site that bundles one of the latest versions of react-modal in IE10.
2. Observe a syntax error (SCRIPT1002 in IE10) in the console.

### Expected behavior:
No syntax error

**Comment by Nicktho** [comment] 2017-04-18 05:39
This issue also pops up when attempting to browserify a module with `react-modal` as a dependency; `The keyword 'const' is reserved `

**Comment by jesstelford** [comment] 2017-04-18 05:54
CC @claydiffrient Looks like the patch releases have caused breaking changes. Do you think it worthwhile reverting until a proper fix is found, or is there a known fix available today?

It looks like the root of the issue is https://github.com/reactjs/react-modal/pull/293/files which removed the `es2015` preset from babel.

**Comment by claydiffrient** [comment] 2017-04-18 13:38
@jesstelford Sorry about that.  It's actually not the problem.  The problem is on our v1 branch and is caused by backporting code between essentially two different code bases.  I'll get a fix up right away.

**Comment by claydiffrient** [comment] 2017-04-18 13:43
Released as v 1.7.7

**Closed by claydiffrient** 2017-04-18 13:43 UTC

**Comment by jacobwgillespie** [comment] 2017-04-18 16:51
It looks like the `v1.7.7` tag wasn't actually pushed to GitHub or npm - can you take a look?  Thanks!

**Comment by claydiffrient** [comment] 2017-04-18 19:39
@jacobwgillespie I guess the release script failed at those points :( . Pushed now.
