### ISSUE TITLE
Omitting afterOpen in the className prop causes "undefined" string in class

### ISSUE THREAD

**Issue by benknight** [reactjs/react-modal#533] opened 2017-10-13 06:33 UTC
### Summary:

Minor, but the string "undefined" is added to the modal element's class attribute when `afterOpen` is omited from the className object, e.g.

```js
<Modal className={{ base: 'modal' }} />
```

### Expected behavior:

"undefined" should never be cast to a string and added to a className.

**Comment by diasbruno** [comment] 2017-10-14 14:59
Hi @benknight, in this case, prefer passing just a string `className={"modal"}`.

**Comment by diasbruno** [comment] 2017-10-14 15:00
I'm tagging as `not a bug`, but perhaps we need to improve the documentation for this case.

**Comment by diasbruno** [comment] 2017-10-17 12:08
@benknight Thanks. Hope my answer helped. I'm closing this for clean up. Please, feel free to reopen this issue.

**Comment by benknight** [comment] 2017-10-17 14:21
Ah I didn't realize jut a string could be passed.  I would suggest using PropTypes to validate.  Something like 

```
className: PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.shape({ ... }),
]),
```

**Comment by diasbruno** [comment] 2017-10-17 14:39
Correct! Can you PR this?

**Comment by diasbruno** [comment] 2017-10-17 14:46
The shape must contain `base`, `afterOpen` and `beforeClose` as `string`.

**Comment by diasbruno** [comment] 2017-10-18 22:20
@benknight Thanks for the suggestion. It'll be available on the next release.

**Closed** 2017-10-18 22:19 UTC
Labels: enhancement, styling

**Comment by benknight** [comment] 2017-10-19 00:08
Great.  I'm happy to PR but it looks like you're all set now.  Thanks for
this improvement!
