### ISSUE TITLE
TypeError: parentInstance.children.indexOf is not a function

### ISSUE THREAD

**Issue by vietnogi** [reactjs/react-modal#553] opened 2017-11-03 18:36 UTC
### Summary:
Getting `TypeError: parentInstance.children.indexOf is not a function` error when using react-test-renderer to write tests.

### Steps to reproduce:

 1. Use react-test-renderer to create a react-modal
 2. Use jest to run test
 3. Get error

### Expected behavior:
No error

### Link to example of issue:

https://github.com/airbnb/enzyme/issues/1150

**Comment by diasbruno** [comment] 2017-11-06 16:33
@vietnogi I'm marking this as duplicated since we already have some issues related to testing...Thank you!

**Comment by RWOverdijk** [comment] 2017-11-20 13:26
@diasbruno Awesome to see you managing issues! But ehm... could you perhaps include the duplicates in this ticket? 😅

**Comment by diasbruno** [comment] 2017-11-20 13:34
@RWOverdijk gee, sorry. I'm trying to keep everything organized, respond issue and stuff, but, you know, time is the problem. Thanks for the heads up and everyone is welcome to contribute to this repo either fixing bugs or helping with management. 👍

**Comment by diasbruno** [comment] 2017-11-20 13:38
...also, this is not an duplicated issue. Perhaps I've overlooked. I'll reopen this.

**Comment by RWOverdijk** [comment] 2017-11-20 13:41
@diasbruno No problem. I know how time consuming it is. Thanks for reopening!

**Comment by kuroshio** [comment] 2018-01-25 02:51
I had the exact same issue, got it working by using enzyme-to-json instead of react-test-renderer

````
import EnzymeToJson from 'enzyme-to-json';
import { mount } from 'enzyme';

test("renders correctly", () => {
    const subject = mount(<YourComponent>);
    expect(EnzymeToJson(subject)).toMatchSnapshot();
});
````

**Comment by reyronald** [comment] 2018-03-07 18:59
Something else that works is mocking the Portal in the top of the test file like this:

```js
jest.mock('rc-util/lib/Portal')
```

Obviosuly you'll need to install the `rc-util` package

**Comment by kylemh** [comment] 2018-09-03 02:03
Wanted to reference some sweet news I saw in another similar issue:
https://github.com/Semantic-Org/Semantic-UI-React/issues/3100#issuecomment-415000769

Sounds like the next React release will have a fix for this 🎉

**Comment by bxt** [comment] 2018-09-03 09:40
This is caused by facebook/react#11565. There is a workaround, which is mocking/overwriting `ReactDOM.createPortal`.

**Comment by devrelm** [comment] 2018-10-15 03:31
Mocking/overwriting `ReactDOM.createportal` won't always work -- it ends up being dependent on the ordering of the imports. This is because the `Modal.js` module [selects the `createPortal` method and saves it to a separate variable when the module inits](https://github.com/reactjs/react-modal/blob/1b561fc54f107df583281667eb92e7975ec33ba8/src/components/Modal.js#L14-L16). Once the method is put in a variable, it can't be changed by mocking/overwriting `ReactDOM.createPortal`.

I'm going to open a PR to put that logic into a method.

**Closed** 2018-10-27 02:03 UTC
Labels: testing

**Comment by q-kirill** [comment] 2021-07-29 11:42
> I had the exact same issue, got it working by using enzyme-to-json instead of react-test-renderer
> 
> ```
> import EnzymeToJson from 'enzyme-to-json';
> import { mount } from 'enzyme';
> 
> test("renders correctly", () => {
>     const subject = mount(<YourComponent>);
>     expect(EnzymeToJson(subject)).toMatchSnapshot();
> });
> ```

thanks, that works!

**Comment by Pacheco95** [comment] 2022-01-31 22:55
I'm facing the same problem. Here I'm using snapshot tests with `react-test-renderer`
```js
import renderer from 'react-test-renderer';

it('should match snapshot', () => {
    const tree = renderer
      .create(<ChangeTitleModal visible oldTitle="Old title" onChange={jest.fn()} onCancel={jest.fn()} />)
      .toJSON();
    expect(tree).toMatchSnapshot();
});
  ```
Does anyone can solve this?

**Comment by Pacheco95** [comment] 2022-01-31 23:10
Found the solution
https://medium.com/@amanverma.dev/mocking-create-portal-to-utilize-react-test-renderer-in-writing-snapshot-uts-c49773c88acd
https://github.com/facebook/react/issues/11565#issuecomment-380143358
