### ISSUE TITLE
React Gateway

### ISSUE THREAD

**Issue by thejameskyle** [reactjs/react-modal#112] opened 2015-12-22 00:59 UTC
In order to render modals at the end of the DOM rather than in place there is a concept of "Portals" which render React DOM into a new context. 

Most implementations of this ([including the one in react-modal](https://github.com/rackt/react-modal/blob/master/lib/components/Modal.js#L7)) work by using:

``` js
ReactDOM.unstable_renderSubtreeIntoContainer(...)
```

and a [little extra magic](https://github.com/rackt/react-modal/blob/master/lib/components/Modal.js#L43-L71) to update the portal appropriately.

The problem with this (other than using an api still marked "unstable") is that it does not work in a server-side/universal/isomorphic context because it works by [creating an element and appending it to `document.body`](https://github.com/rackt/react-modal/blob/master/lib/components/Modal.js#L44-L46).

Obviously this is not an ideal solution, so I've created a new way of doing this that fits within the normal react rendering cycle.

``` html
<GatewayProvider>
  <div className="application">
    <div className="application-content">
      <Gateway into="example">
        Hello from Gateway
      </Gateway>
    </div>
    <GatewayDest name="example" className="gateway"/>
  </div>
</GatewayProvider>
```

Which will render like this:

``` html
<div class="application">
  <div class="application-content"></div>
  <div class="gateway">
    Hello from Gateway
  </div>
</div>
```

It does this by maintaining an internal registry which tracks containers and children and renders them using the normal react component lifecycle. I've published this module as [`react-gateway`](https://github.com/cloudflare/react-gateway)

I've used this to create a React modal library that can be rendered universally: [`react-modal2`](https://github.com/cloudflare/react-modal2) (note this is not a drop-in replacement, it has a different/less-opinionated api).

I think it would be really awesome if `react-modal` could do the same and use `react-gateway` too.

**Comment by mjackson** [comment] 2016-01-14 01:24
Thanks for bringing this up, @thejameskyle :)

ping @mzabriskie @ryanflorence 

What do you guys think of the react-gateway approach? I'm not very knowledgeable about modals, but I figured you might have some opinions.

**Comment by mjackson** [comment] 2016-02-03 19:04
ping @ryanflorence Can you please take a look here?

**Comment by dferber90** [comment] 2016-05-25 11:42
Can anyone give an update on the status of this? Was there a specific reason not to go with it?

`react-hot-loader` v3 will use [react-deep-force-update](https://github.com/gaearon/react-deep-force-update). I think hot-loading anything in modals will not work with `react-hot-loader` v3 since the portal used here does not obey the react component lifecycle, so the contents can not be force-updated after a hot-load. I noticed this in our application, but it is a huge one so I'm not 100% certain I identified the problem correctly.

Can you confirm the assumption that "deep-forcing updates of portals will not work" is correct @gaearon?

**Comment by gaearon** [comment] 2016-05-25 11:46
I don't see why it wouldn't work. It renders in componentWillReceiveProps which should be enough. Can you please file an issue with RHL and a minimal reproducing case?

**Comment by dferber90** [comment] 2016-05-25 11:50
Thanks for the fast response! :)

As I said I'm not 100% certain I identified the problem correctly. I'll take another look and try to set up a reproduction repo. Wanted to confirm before I go through the trouble of setting it up. If I can reproduce, I'll file an issue in RHL.

**Comment by gaearon** [comment] 2016-05-25 11:51
Thanks!

**Comment by dferber90** [comment] 2016-05-25 13:30
To my surprise I was not able to reproduce. Seems like the issue is somewhere else. Sorry for the noise everybody 🙄

**Comment by diasbruno** [comment] 2017-06-24 18:37
Closing this for clean up. Thank you all.

**Closed by diasbruno** 2017-06-24 18:37 UTC

**Comment by OliverJAsh** [comment] 2019-05-04 14:10
IIUC, SSR of the modal does not work because the modal uses portals. This proposal offers a solution. Is that correct?

I for one would very much like a solution to enable SSR for the modal

Re. https://github.com/reactjs/react-modal/issues/580#issuecomment-489330313
