### ISSUE TITLE
owner ref errors on open/close

### ISSUE THREAD

**Issue by mgenev** [reactjs/react-modal#118] opened 2016-01-21 00:40 UTC
I implemented by copy/pasting the docs, but when I open I get this error and it does open.

```
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

and when I try to I get this error, and it fails to close:

```
Uncaught Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

**Comment by JeffGuKang** [comment] 2016-01-22 04:58
I have same errors in react v0.14.6.

**Comment by davidwadge** [comment] 2016-03-23 11:50
@mgenev Did you manage to resolve this in the end?

**Comment by JeffGuKang** [comment] 2016-03-24 04:54
@davidwadge I resolved through deleting modules and reinstalling.

**Comment by danbovey** [comment] 2016-04-22 20:33
https://github.com/reactjs/react-modal/issues/146 is a duplicate of this but I commented on there about a potential fix (upgrading to `react@15.0.1` and `react-modal@1.2.0` seemed to solve it for me)

**Comment by john-osullivan** [comment] 2016-06-04 00:28
Hey, I'm running on `react@15.0.2` and `react-modal@1.3.0` and still getting this bug on some modals.  It's particularly weird because it doesn't happen everywhere, only on one particular modal.  Based on how other people resolved this, any ideas on how I can fix it?

**Comment by dcaillibaud** [comment] 2016-06-22 12:52
Same here with react 15.1.0 and react-modal 1.3.0, if I put in modal one of my own Component (statefull) I have this error (Only a ReactOwner can have refs…), not found any workaround…

**Comment by jovinbm** [comment] 2016-08-21 11:33
In my case, I had loaded multiple versions of `react` without knowing. I had separated `react` into a vendor bundle and using `browserify-shim` to resolve the requires. `react-modal` also requires `react` and so it was loading it's own react since `browserify` does not execute transforms for required modules.

Simply put, I changed `transform('browserify-shim')` to `transform({global: true}, 'browserify-shim')` and everything was fine. You could also add the specific transform to `react-modal`'s package.json and it would work.

**Comment by GBarthos** [comment] 2017-01-31 19:52
Hi, I'm using react 15.4.0 and react-modal 1.6.5, same thing here.

What is causing this ? Isn't there any fix ?

**Comment by diasbruno** [comment] 2017-06-24 17:41
This issue must be fixed on current version `v2+`. 

I'm closing this issue for clean up. Please, feel free to reopen this issue if needed. 
Thank you!

**Closed by diasbruno** 2017-06-24 17:41 UTC
