### ISSUE TITLE
Close Modal when clicking outside the modal

### ISSUE THREAD

**Issue by vgoklani** [reactjs/react-modal#690] opened 2018-09-27 03:16 UTC
Hello - thanks for creating this!

Quick question - how do I configure the modal to close when the user clicks outside the modal? The current implementation requires the user to close the modal by pressing the "ESC" button while the mouse is over the modal. 

Thanks!

**Comment by konekoya** [comment] 2018-09-27 05:36
Do you use `onRequestClose` prop? It works correctly in this [example](https://codepen.io/claydiffrient/pen/KNjVBx)

**Comment by diasbruno** [comment] 2018-09-30 00:31
@vgoklani Have you find a solution for this issue?

**Comment by vgoklani** [comment] 2018-10-05 22:14
@diasbruno I have not found a solution.

@konekoya I used the onRequestClose as below:

	<Modal
		style={customStylesDarkTheme}
		closeTimeoutMS={10}
		isOpen={this.state.modalIsOpen}
		onRequestClose={this.handleModalCloseRequest}>
		<div>
			<p key={this.props.message.id + "bodyContent"} dangerouslySetInnerHTML={{ __html:this.props.message.body}}/>
		</div>
	</Modal>

**Comment by diasbruno** [comment] 2018-10-05 22:36
Ah! This is what you are looking for...

 [Using shouldCloseOnOverlayClick](http://reactcommunity.org/react-modal/examples/should_close_on_overlay_click.html)

**Comment by vgoklani** [comment] 2018-10-05 23:15
I tried this, but it didn't work:

	<Modal
		style={customStylesDarkTheme}
		closeTimeoutMS={10}
		isOpen={this.state.modalIsOpen}
		shouldCloseOnOverlayClick={true}
		onRequestClose={this.handleModalCloseRequest}>
		<div>
			<p key={this.props.message.id + "bodyContent"} dangerouslySetInnerHTML={{ __html:this.props.message.body}}/>
		</div>
	</Modal>

**Comment by konekoya** [comment] 2018-10-06 00:27
I think it would be better If you can put your code on [codesanbox ](https://codesandbox.io/)(or something similar) to reproduce the bug. That way, it will be a lot easier for people to help out.

**Comment by dominikabieder** [comment] 2019-12-04 11:15
I have the same issue, I have both onRequestClose and shouldCloseOnOverlayClick, the modal doesn't close when I click outside of the popup to close it. I am using react hooks.

```
const ReviewSection = () => {
  const [ isOpen, setIsOpen ] = useState(false)
  return (
  ....
  <ModalPopup className='CodeOfConductPopup' isOpen={isOpen} onRequestClose={() => 
  setIsOpen(false)} shouldCloseOnOverlayClick={true}>
        <ReviewCodeOfConductContent onCancel={() => setIsOpen(false)} />
  </ModalPopup>
 )
}

**Comment by thunder87** [comment] 2019-12-09 14:58
Had the same issue as @dominikabieder - you need **onRequestClose**
See the example here: [https://codepen.io/claydiffrient/pen/woLzwo](https://codepen.io/claydiffrient/pen/woLzwo)

**Comment by marco-000** [comment] 2020-03-30 17:30
Any update on this issue?


> Had the same issue as @dominikabieder - you need **onRequestClose**
> See the example here: https://codepen.io/claydiffrient/pen/woLzwo
your codepen is not working. when I click outside the modal it isn't closing.

**Comment by denisgrabina** [comment] 2020-04-14 19:01
Still no solutions? 😞

**Comment by diasbruno** [comment] 2020-04-14 22:31
Hi @denisgrabina @marco-000,  which react version are you using? Can you provide an example?

**Comment by diasbruno** [comment] 2020-04-14 22:35
From the docs:

    - Boolean indicating if the overlay should close the modal
    shouldCloseOnOverlayClick={true}

    - Function that will be run when the modal is requested
    - to be closed (either by clicking on overlay or pressing ESC).
    - Note: It is not called if isOpen is changed by other means.
    onRequestClose={handleRequestCloseFunc}

Remember that `handleRequestCloseFunc` must set the variable used on `isOpen` to `false`.

If this doesn't work, we may have a problem.

**Comment by marco-000** [comment] 2020-04-17 18:35
@diasbruno Yes I got it working with the `onRequestClose`. Thank you.

**Comment by diasbruno** [comment] 2020-04-17 20:42
Awesome,  @marco-000.

I'm going to close this issue, since we can't confirm that it is a bug.

@denisgrabina, reopen if you need any help with this.

**Closed by diasbruno** 2020-04-17 20:42 UTC
Labels: question

**Comment by andyseracuse** [comment] 2020-11-19 18:38
this is most definitely a bug.  We found a workaround with the following.

add stopPropogation to the code and it will work. i.e. (using the code from @dominikabieder above)  ...

`const ReviewSection = () => {
  const [ isOpen, setIsOpen ] = useState(false)
  return (
  ....
  <ModalPopup 
        className='CodeOfConductPopup' 
        isOpen={isOpen} 
        onRequestClose={(e) => e.stopPropogation(); setIsOpen(false);} 
        shouldCloseOnOverlayClick={true}
  >
    <ReviewCodeOfConductContent onCancel={() => setIsOpen(false)} />
  </ModalPopup>
 )
}`

**Comment by DeMokry** [comment] 2020-12-23 10:38
I found a solution in  backdrop option. 
```
 <Modal
        show={show}
        onHide={handleClose}
        backdrop="static"
        keyboard={false}
      >
```
Link: https://react-bootstrap.github.io/components/modal/#static-backdrop

**Comment by carlosahued** [comment] 2022-04-11 21:22
Solution for when the modal does not close when clicking right on the container and only closes when doing outside.

let menuRef = useRef<HTMLDivElement>(null)

  const handleClick = ( e: FormEvent<HTMLInputElement> ) => {
    if( e.target === menuRef.current ){
      closeDrop(false)
    }
  }

<div ref={menuRef} onClick={ () => handleClick }>
   Hello!
</div>

**Comment by carlosahued** [comment] 2022-04-11 21:24
Solution for when the modal does not close when clicking right on the container and only closes when doing outside.

`
let menuRef = useRef<HTMLDivElement>(null)

  const handleClick = (e: FormEvent<HTMLInputElement>) => {
    if( e.target === menuRef.current ){
      closeDrop(false)
    }
  }

<div ref={menuRef} onClick={ () => handleClick }>
   Hello
</div>

`

**Comment by GorkemSahin** [comment] 2022-04-22 10:08
Those of you who are having this problem is probably because you're setting ReactModal CSS to occupy the whole width and height of the screen using the `className` prop, so no click registers as an outside click.

**Comment by dminazarov** [comment] 2024-02-08 13:56
Clicking event is triggered in ` .modal` div. I think that it should be in `.modal-dialog`.
Anyways, you can add custom styles or override `.modal` style to keep `.modal-dialog` body width & height.
` 
inset: 50% auto auto 50%;
margin-right: -50%;
transform: translate(-50%, -50%);
`
