### ISSUE TITLE
Couldn't find preset "stage-2" relative to directory "..\\react-modal"

### ISSUE THREAD

**Issue by MZShahbaz** [reactjs/react-modal#450] opened 2017-07-02 08:37 UTC
After running the command:
npm install react-modal

It prompt me with: 
+ react-modal @2.2.1

When i imported it in one of my file by:
import ReactModal from 'react-modal';

I got errors:
ERROR in ./~/react-modal/lib/index.js
Module build failed: Error: Couldn't find preset "stage-2" relative to directory "***\\react-modal"
    at ***\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (***\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (***\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (***\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (***\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (***\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (***\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (***\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (***\node_modules\babel-loader\lib\index.js:46:20)
 @ ./src/conatainers/App.js 11:18-40
*** is starting path that i have replaced.

**Comment by diasbruno** [comment] 2017-07-02 13:48
Hi @MZShahbaz, sometimes I got this, because I'm forget if I'm using `yarn` or `npm`. :)
It should not be required `stage-2`, because `react-modal@2.2.1` is compiled to `es2015` before send to `npm`.

**Comment by MZShahbaz** [comment] 2017-07-02 16:36
Thanks @diasbruno but my problem persists... 
In my package.json file, I have;
"babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }
as es2015 is available for babel, why am i getting this error?
how may i fix it?

**Comment by diasbruno** [comment] 2017-07-02 16:48
Probably adding "stage-2" to your list of presets and `npm install --save-dev babe-preset-stage-2` or `yarn add --dev babe-preset-stage-2`.

**Comment by MZShahbaz** [comment] 2017-07-02 17:01
Thanks a lot @diasbruno , this has fixed my error...
No words to thank you (Y)

**Comment by diasbruno** [comment] 2017-07-02 17:05
Great! This a little bit weird. Maybe later I'll try to reproduce this issue (since react-modal should not require `stage-2`).
Thank you!

**Comment by uhef** [comment] 2017-07-09 16:08
I had the same problem as well.

This should probably be fixed within react-modal as it seems awkward to have to pollute the babel preset list of the consuming project to fix this...

**Comment by uhef** [comment] 2017-07-09 16:16
Actually, downgrading to 1.9.7 seems to solve the problem as this is introduced in 2.0.0:

https://github.com/reactjs/react-modal/blob/v2.0.0/.babelrc#L2

**Comment by diasbruno** [comment] 2017-07-09 16:41
@uhef please check if `babel-preset-stage-2` is on package.json. It should not be a problem unless you have an old fork of react-modal and missed to `npm install` (or yarn).

**Comment by uhef** [comment] 2017-07-10 06:34
Adding `babel-preset-stage-2` as a dev dependency in the host project package.json fixes the issue. If this is how it should be fixed I suppose `react-modal` should list `babel-preset-stage-2` as a peer dependency.

**Comment by diasbruno** [comment] 2017-07-10 12:23
I don't know, probably there is something wrong on the build process to publish to npm.

**Comment by diasbruno** [comment] 2017-07-10 12:31
@uhef Did you tried to update `react-modal` or started a new project?

**Closed** 2017-12-04 16:48 UTC

**Comment by diasbruno** [comment] 2017-12-04 17:24
Released `v3.1.7`.
