### ISSUE TITLE
Accessibility: focus trap improvements to avoid accessing underlying page

### ISSUE THREAD

**Issue by hollowaysmith** [reactjs/react-modal#787] opened 2019-11-13 19:25 UTC
### Summary:

While doing an accessibility audit of a site an auditor was able to escape the modal's focus trap.

This does seem like an accessibility issue because,

1. For sighted users with screen readers the background page (below the modal) can be navigated and yet the modal itself obscures the background, and the easiest way to find the modal again is to use a mouse which they may not have.
2. For screen reader users with sight impairments it can be hard to find the modal again.

### Steps to reproduce:

 1. https://cdpn.io/holloway/fullpage/eYYPppW
 2. Open modal
 3. `CTRL-L` to move focus to address bar
 4. `<tab>` back into page and you can see the first button under the modal receives focus. This button will turn green when it receives focus.

Also  **`<SHIFT>`**+`<tab>` to navigate back into page from the bottom and the same issue happens (although that codepen doesn't show it).

### Expected behavior:

`<tab>`ing back into the page moves focus to the modal.

### Potential Fix

While a modal is open we could temporarily insert some focusable elements as the first child and last child of `<body>` that immediately move focus to the modal content. I guess these could be just `<div tabindex="0"></div>` elements.

I'm not sure how this would work with nested modals. Perhaps we'd restore focus to the most recently opened modal.

Do you want a PR?

If so, any advice on how to implement this?

I think this needs to be plain JS (not React) to ensure these `<div tabindex="0" />` elements are the first and last in `<body>`, but obviously we'd use lifecycle methods to clean up if React Modal was unmounted.

**Comment by holloway** [comment] 2019-11-14 03:59
Duplicate of #742

**Comment by diasbruno** [comment] 2019-11-15 13:21
I'm going to close this one in favor of #742.

Thanks, @hollowaysmith @holloway.

**Closed by diasbruno** 2019-11-15 13:21 UTC
