### ISSUE TITLE
Opening modal causes body scroll top or bottom

### ISSUE THREAD

**Issue by prztrz** [reactjs/react-modal#585] opened 2017-12-18 22:30 UTC
I have an issue that wehever I open the modal the body is immediatelly scrolled  to top or to bottom of the website. When the modal is closed the user is not in the place he/she opened the modal but either on the top or on the bottom of website.

I used following CSS to prevent parent element from scrolling (it allways causes the body scrolling top when modal is opened):

```css
.ReactModal__Body--open {
    overflow: hidden;
    position: fixed;
    width: 100%;
}
```

When I try to use just ```overflow:hidden``` as recommended in readme.md it does not work for me - the parent element is still scrollable.
When I try to use it without ```position: fixed``` as below: 

```css
.ReactModal__Body--open {
    overflow: hidden;
    width: 100%;
}
```
It always causes the body scroll bottom when modal is opened.

Skipping ```width: 100%``` causes the body content is shifted to the left if ```position: fixed``` is used as well.

**Comment by ryansukale** [comment] 2017-12-29 19:00
Until now I was only seeing the issue in firefox.
But as of today, this is happening in on both firefox and chrome.

**Comment by lydell** [comment] 2018-01-03 12:01
Wild guess: Could it be that you have something like:

```jsx
<a href="#" onClick={() => this.openModal()}>Open modal</a>
```

and forgot `event.preventDefault()`? (You could also use a `<button>`.)

```jsx
<a href="#" onClick={event => {event.preventDefault(); this.openModal()}}>Open modal</a>
```

**Comment by prztrz** [comment] 2018-01-03 12:35
@lydell unfortunatelly this is not the problem in my case. Clickable elements are ```<div aria-role="button">``` those should not cause automatically reload page by default, however I tried ```event.preventDefault()``` anyway and it did not work.

For now I worked the problem around engaging state and additional scrollBack() function like here:
```
//changing modal isOpen prop to true
//param scrollPos is a number returned by window.scrollY
openModal = scrollPos => { 
    this.setState({
        isModalOpen: true,
        scrollPosOnModalOpen: scrollPos
    })
}

onRequestClose = () => {
    this.setState({
        isModalOpen: false,
   }, this.scrollBack)
}

scrollBack = () => {
     window.scrollTo(0, this.state.scrollPosOnModalOpen)
}

```

Well it works but does not look very efficient.

**Comment by diasbruno** [comment] 2018-01-03 12:45
@prztrz @lydell @ryansukale Can you check if #588 can help with this issue?

**Comment by prztrz** [comment] 2018-01-03 13:02
@diasbruno thank you, this solution solved my problem.

**Comment by diasbruno** [comment] 2018-01-03 13:23
Please, if you have some time available, go ahead and review the PR. :)

**Comment by woniesong92** [comment] 2018-02-21 14:51
@diasbruno is there any other reason why setting both `.ReactModal__Body--open` and `.ReactModal__Html--open` to hide overflow not prevent the scrolling? I confirmed that the classes and styles are added but it still scrolls to top when the modal is open.

**Comment by diasbruno** [comment] 2018-02-21 14:58
@woniesong92 Can you make a simple example for this case?

**Comment by webmastervishal** [comment] 2018-07-09 11:19
@prztrz what changes you made to resolve your issue, can you mention it here, I am also having the same issue when modal is open the page is scrolled automatically to the bottom of the page. I read about the solution given above but got nothing from it which can work fine for me.

**Comment by Kelby2** [comment] 2018-07-16 20:08
+1, I'm still having this issue with v3.5.1. Upon opening the window, the background scrolls all the way to the bottom. Really breaks the UX flow when you close the modal and find yourself at the bottom of the page. I've added the 

```htmlOpenClassName='ReactModal__Html--open```

prop and have set the ```overflow: hidden```'s, but this is still occurring.

**Comment by prztrz** [comment] 2018-07-16 21:45
@webmastervishal in general adding `overflow: hidden` to `html` tag solved the problem.

**Comment by Kelby2** [comment] 2018-07-19 04:37
@webmastervishal I was able to stop the scrolling by adding `position: fixed` to `.ReactModalPortal`

CSS:
```
.ReactModal__Body--open {
  position: static;
  overflow-y: scroll;
}

.ReactModal__Html--open {
  overflow-y: hidden;
}

.ReactModalPortal {
  position: fixed;
  z-index: 1 !important;
}
```

Also remember to pass `htmlOpenClassName='ReactModal__Html--open'` prop to the Modal.

**Comment by Teranjit** [comment] 2018-09-12 07:18
If you use an element that doesn't have a tabindex attribute by default, adding one to the element solved the issue for me.
i.e <img onClick={() => this.openModal() tabindex='0'/>

**Comment by TheMangoTrain** [comment] 2019-08-04 02:46
Just adding an outsider perspective. I've dealt with the OP's problem (background jumps to top when opening modal) with vanilla JS modals and the culprit is often the <a href="#"> and how a browser deals with "#".

Consider making your clickable element _not_ <a>, perhaps a button or just a plain div with a listener. In any case, semantically, should an <a> be used for anything other than an actual link?

**Comment by TheCraftConsulting** [comment] 2019-08-09 11:02
Fixed it! Delving into the code...

body.modal-open {position:static !important; overflow:visible; padding:0 !important;}

**Comment by jaybabak** [comment] 2019-09-17 14:00
The right answer is by @TheMangoTrain, the "#" value to the <a> element with href attribute is what causes the page to jig, so changing the element to a <button> will resolve the issue! Thanks @TheMangoTrain

**Comment by maxwaiyaki** [comment] 2020-05-12 11:40
> 
> 
> @webmastervishal I was able to stop the scrolling to top/bottom on open behavior by adding `position: fixed` to `.ReactModalPortal`
> 
> CSS:
> 
> ```
> .ReactModal__Body--open {
>   position: static;
>   overflow-y: scroll;
> }
> 
> .ReactModal__Html--open {
>   overflow-y: hidden;
> }
> 
> .ReactModalPortal {
>   position: fixed;
>   z-index: 1 !important;
> }
> ```
> 
> Also remember to pass `htmlOpenClassName='ReactModal__Html--open'` prop to the Modal.

This works for me but is this the solution or just a walkaround as we wai for the problem to be fixed in the package??

**Comment by kolnogorov** [comment] 2020-10-29 10:25
After three years this is still opened, jeez.

**Comment by esp-tuyen** [comment] 2023-03-07 03:11
> ```
> .ReactModal__Body--open {
>   position: static;
>   overflow-y: scroll;
> }
> 
> .ReactModal__Html--open {
>   overflow-y: hidden;
> }
> 
> .ReactModalPortal {
>   position: fixed;
>   z-index: 1 !important;
> }
> ```

This works for me, thanks !

**Comment by esp-tuyen** [comment] 2023-03-07 03:11
> Wild guess: Could it be that you have something like:
> 
> ```js
> <a href="#" onClick={() => this.openModal()}>Open modal</a>
> ```
> 
> and forgot `event.preventDefault()`? (You could also use a `<button>`.)
> 
> ```js
> <a href="#" onClick={event => {event.preventDefault(); this.openModal()}}>Open modal</a>
> ```
> 
> Edit: I think this is a duplicate of [#117 (comment)](https://github.com/reactjs/react-modal/issues/117#issuecomment-333409035)

This works for me, thanks !

**Comment by diasbruno** [comment] 2023-03-07 14:30
This is not a react-modal bug, it's a browser behavior.
Each browser does its own thing, so it's hard to get it right.

There are better packages that helps preventing/normalize this behavior across different browsers.

**Comment by diasbruno** [comment] 2023-03-07 14:32
I'm going to close this one, but please feel free to open a discussion if react-modal should add a package to deal with this, or, users should be free to choose.

**Closed by diasbruno** 2023-03-07 14:32 UTC
Labels: not a bug, browser api
